Repository wazuh/wazuh-ruleset, pull requests merged in 2019-08, with the labels that each got.

#460 3.10 New rule for Windows
  rules/0590-win-system_rules.xml
Labels: enhancement, rules

#425 Cisco ASA decoders and rules
  decoders/0064-cisco-asa_decoders.xml
  rules/0665-cisco-asa_rules.xml
  tools/rules-testing/tests/cisco_asa.ini
Labels: decoders, operations, rules

#323 Ssh recon
  decoders/0450-openvas_decoders.xml
  rules/0020-syslog_rules.xml
  rules/0095-sshd_rules.xml
  rules/0285-systemd_rules.xml
  rules/log-entries/kernel
Labels: community

#458 Fix rules about shellshock attack
  rules/0245-web_rules.xml
  rules/0250-apache_rules.xml
Labels: bug, rules

#239 Update 0285-systemd_rules.xml
  decoders/0350-unix_decoders.xml
  rules/0285-systemd_rules.xml
  tools/rules-testing/tests/systemd.ini
Labels: operations

#410 Extract the srcip and more infos from one postfix message.
  decoders/0220-postfix_decoders.xml
Labels: community, enhancement, rules

#144 fix false positives on /etc/hosts caused by unescaped . character
  rootchecks/rootkit_trojans.txt
Labels: community

#354 Add support for NAXSI web application firewall
  decoders/0170-nginx_decoders.xml
  rules/0260-nginx_rules.xml
Labels: community

#220 Update to windows defender decoder
  decoders/0380-windows_decoders.xml
Labels: community

#461 Software Restriction Policy rules
  rules/0585-win-application_rules.xml
Labels: operations

#154 3.3 fix windows decoder
  decoders/0380-windows_decoders.xml
Labels: enhancement, operations

#440 Checkpoint Smart1 firewalls - new Decoders and Rules
  decoders/0051-checkpoint-smart1_decoders.xml
  rules/0680-checkpoint-smart1_rules.xml
  tools/rules-testing/tests/checkpoint_smart1.ini
Labels: decoders, operations, rules

#437 Panda-PAPS new decoders and rules
  decoders/0470-panda-paps_decoders.xml
  rules/0675-panda-paps_rules.xml
  tools/rules-testing/panda_paps.ini
Labels: enhancement, operations

#274 Fix 0295-sonicwall_decoders.xml
  decoders/0295-sonicwall_decoders.xml
  tools/rules-testing/tests/SonicWall.ini
Labels: operations

#327 Create 0585-vipre_rules.xml
  rules/0585-vipre_rules.xml
Labels: enhancement, operations
