Repository wazuh/wazuh-ruleset, pull requests merged in 2019-06, with the labels that each got.

#416 Added functionality to remove standards
  tools/map-security-standard/map_standard.py
Labels: enhancement, rules

#420 Fix check 11522 of Solaris SCA policy
  sca/sunos/cis_solaris11_rcl.yml
Labels: bug

#421 Script to map the standards in sca
  sca/applications/cis_apache2224_rcl.yml
  sca/applications/cis_mysql5-6_community_rcl.yml
  sca/applications/cis_mysql5-6_enterprise_rcl.yml
  sca/darwin/15/cis_apple_macOS_10.11.yml
  sca/darwin/16/cis_apple_macOS_10.12.yml
  sca/darwin/17/cis_apple_macOS_10.13.yml
  sca/darwin/web_vulnerabilities.yml
  sca/debian/cis_debian_linux_rcl.yml
  sca/debian/cis_debianlinux7-8_L1_rcl.yml
  sca/debian/cis_debianlinux7-8_L2_rcl.yml
  sca/generic/system_audit_pw.yml
  sca/generic/system_audit_ssh.yml
  sca/generic/web_vulnerabilities.yml
  sca/rhel/5/cis_rhel5_linux_rcl.yml
  sca/rhel/6/cis_rhel6_linux_rcl.yml
  sca/rhel/7/cis_rhel7_linux_rcl.yml
  sca/sles/11/cis_sles11_linux_rcl.yml
  sca/sles/12/cis_sles12_linux_rcl.yml
  sca/sunos/cis_solaris11_rcl.yml
  sca/windows/acsc_office2016_rcl.yml
  sca/windows/cis_win10_enterprise_L1_rcl.yml
  sca/windows/cis_win10_enterprise_L2_rcl.yml
  sca/windows/cis_win2012r2_domainL1_rcl.yml
  sca/windows/cis_win2012r2_domainL2_rcl.yml
  sca/windows/cis_win2012r2_memberL1_rcl.yml
  sca/windows/cis_win2012r2_memberL2_rcl.yml
  sca/windows/win_audit_rcl.yml
Labels: SCA, enhancement

#419 Mapping script for HIPAA and NIST 800 53 to compliance in SCA policies
  tools/map-security-standard/map_standard_yaml.py
Labels: SCA, enhancement

#246 Fix auditd decoders
  decoders/0040-auditd_decoders.xml
Labels: community, decoders

#412 Remove tailing single quote from audit.res
  decoders/0040-auditd_decoders.xml
Labels: community, decoders

#243 0170-nginx_decoders.xml: Make server: content optional
  decoders/0170-nginx_decoders.xml
Labels: community
