Repository wazuh/wazuh-ruleset, pull requests merged in 2019-02, with the labels that each got.

#289 Added cis_win2012r2_memberL2_rcl.yml
  configuration-assessment/windows/cis_win2012r2_memberL2_rcl.yml
Labels: enhancement

#293 Improve rules for Docker listener
  rules/0560-docker_integration_rules.xml
Labels: enhancement

#302 Add new <same_field> option to eventchannel
  rules/0220-msauth_rules.xml
Labels: bug

#301 Improve Audit decoders
  decoders/0040-auditd_decoders.xml
Labels: bug, enhancement
