Repository wazuh/wazuh-ruleset, pull requests merged in 2020-12, with the labels that each got.

#810 Update 0245-web_rules.xml
  rules/0245-web_rules.xml
Labels: operations

#811 4.0 update web rules
  CHANGELOG.md
  rules/0245-web_rules.xml
Labels: operations

#503 Fix SonicWall decoder prematch
  decoders/0295-sonicwall_decoders.xml
Labels: decoders, operations

#768 Adapt rules to the new Windows registry monitoring
  rules/0015-ossec_rules.xml
Labels: core/fim, core/fim/registry, rules, windows

#815 Updating the README file to provide information about the new location of the Wazuh ruleset
  README.md
Labels: enhancement
